# 🍰 Betty’s Bakery: NumPy Practice

This notebook contains my personal work on **NumPy arrays** as part of Codecademy's *"Betty’s Bakery"* exercise. The prompt and general structure were provided by Codecademy, but all code, notes, and explanations are my own.

---

### 🧠 Focus Areas
- Creating and manipulating NumPy arrays
- Practicing indexing, slicing, and reshaping
- Reinforcing foundational NumPy skills in a real-world-style scenario

This exercise is part of my ongoing [Data Practice Journal](https://github.com/jennifer-marie-nyc/data-practice-journal), where I document consistent coding work, build fluency, and connect technical skills to behavioral insights and future projects.


In [2]:
import numpy as np

In [3]:
cupcakes = np.array([2, 0.75, 2, 1, 0.5])

In [7]:
recipes = np.genfromtxt("recipes.csv", delimiter=",")

In [8]:
print(recipes)

[[2.    0.75  2.    1.    0.5  ]
 [1.    0.125 1.    1.    0.125]
 [2.75  1.5   1.    0.    1.   ]
 [4.    0.5   2.    2.    0.5  ]]


In [16]:
# The 3rd column represents the number of eggs that each recipe needs.

# Select all elements from the 3rd column and save them to the variable eggs.

eggs = recipes[: ,2]
print(eggs)

[2. 1. 1. 2.]


In [17]:
# Which recipes require exactly 1 egg? Use a logical statement to get True or False for each value of eggs.
eggs == 1

array([False,  True,  True, False])

In [18]:
# Betty is going to make 2 batches of cupcakes (1st row) and 1 batch of cookies (3rd row).

# You already have a variable for cupcakes. Create a variable for cookies with the data from the 3rd row.

cookies = recipes[2, :]
print(cookies)

[2.75 1.5  1.   0.   1.  ]


In [19]:
# Get the number of ingredients for a double batch of cupcakes by using multiplication on cupcakes. Save your new variable to double_batch.

double_batch = cupcakes * 2

print(double_batch)

[4.  1.5 4.  2.  1. ]


In [20]:
# Create a new variable called grocery_list by adding cookies and double_batch.
grocery_list = cookies + double_batch
print(grocery_list)

[6.75 3.   5.   2.   2.  ]
