# 🧪 Practicing NumPy in Python

This notebook includes selected notes and practice examples from Codecademy’s *Introduction to NumPy* module. Rather than documenting every step, I’ve focused on the concepts that felt most relevant to reinforce, revisit, or apply in future analysis.

---

### Why NumPy?

Although I’ve worked with statistical concepts in R (including multivariate modeling during my MA in psychology), I’m still building fluency in Python. NumPy offers a fast, flexible way to perform calculations and manipulate numerical data—especially useful when I start working with behavioral datasets or preparing data for storytelling.

---

This is part of my ongoing effort to connect past training with new tools, and to make my learning process visible as I build toward more complex, project-based work.


In [2]:
import numpy as np

### Two-Dimensional Arrays
Multiple arrays can be stored in a single two-dimensional array:

In [3]:
np.array([[10, 11, 12, 13, 14, 15],
         [20, 21, 22, 23, 24, 25],
         [30, 31, 32, 33, 34, 35]])

array([[10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35]])

Two-dimensional arrays have the same number of elements.
For example, the following is NOT a two-dimensional array:
(Note, in NumPy 2.0 and above, the below will raise a `ValueError`:

```python
np.array([[1,2,3],
          [21, 22]])
```

### Accessing NumPy Array Elements by Index
Like Python lists, NumPy arrays are **zero-indexed**

Example:

In [5]:
new_array = np.array([0, 1, 2, 3, 4, 5, 6])
print(new_array[0])
print(new_array[4])

0
4


**Negative indices** are used to count from the opposite end of the array and start with `-1`

In [7]:
print(new_array[-1])
print(new_array[-4])

6
3


To select **multiple elements** in the array, define a range.
In the folowing example `new_array[2:5]` will select all alements from `new_array[2]` to `new_array[5]`, *including* `new_array[2]` but *excluding* `new_array[5]`

In [9]:
print(new_array[2:5])

[2 3 4]


To select **all elements *before*** `new_array[4]`, use:

In [11]:
print(new_array[:4])

[0 1 2 3]


**Negative indices** can also be used to select multiple elements. The following will select the last 4 elements in the array:

In [12]:
print(new_array[-4:])

[3 4 5 6]
